### ISSUE TITLE
Class ColorSensor __init__ bug

### ISSUE THREAD

**Issue by misolietavec** [QuirkyCort/ev3dev-lang-python-fast#3]
The correct `__init__` should be:
```python
  def __init__(self, address=None):
    self.red_max = 300
    self.green_max = 300
    self.blue_max = 300
    super().__init__(address)
```

**Comment by QuirkyCort** [comment]
Sorry for the late reply. Not used to github and didn't realize that I have to watch the repository to be notified of new issues even if I'm the owner.

You're right about the error. I've since corrected it. Don't have my EV3 with me now, so I'll close the issue when I have some time to test it.
