### ISSUE TITLE
ColorSensor in __init__ AttributeError: type object 'super' has no attribute '__init__'

### ISSUE THREAD

**Issue by DanieleBenedettelli** [QuirkyCort/ev3dev-lang-python-fast#4]
I am trying the benchmark file found here
with the shebang 
'''
#!/usr/bin/env python3
'''
https://www.aposteriori.com.sg/ev3fast-a-python-module-for-faster-ev3-interface/
if I decomment 
'''
from ev3fast import *
'''
this error is generated at runtime:

  File "/home/robot/testSensorSpeed/ev3fast.py", line 251, in __init__
AttributeError: type object 'super' has no attribute '__init__'

I changed the __init__ method in the ColorSensor as indicated in the other Issue.
Please help!
TIA

**Comment by QuirkyCort** [comment]
Sorry for the late reply. Not used to github and didn't realize that I have to watch the repository to be notified of new issues even if I'm the owner.

I think you didn't make the change correctly. There were two mistakes in my original file, "super" needs to be changed to "super()". The second mistake was the "self" which needs to be removed. I've corrected both errors on github. You can try it again.

I didn't test out the last PR thoroughly before (...or even after) accepting it. My bad.
