### ISSUE TITLE
Making this compatible with micropython

### ISSUE THREAD

**Issue by stephan-ack** [QuirkyCort/ev3dev-lang-python-fast#5]
Currently this library uses os.py with some functions not supported by micropython (i.e. lseek), would anyone be able to make a different implementation that supports micropython instead?

Would make booting and execution speed (I think) even better.

/Stephan

**Comment by QuirkyCort** [comment]
I've started a micropython branch that might work. It basically replaces os.open with the io.open if it detects micropython.

Unfortunately, I don't have the opportunity to test it out. If you're able to test it, note that only the base sensor class and the touch sensor are modified to work with micropython (...motors and all other sensors are not modified). If it works, I'll do the rest.

Part of the reason why ev3fast performs better than the normal ev3dev-lang-python, is because it use os.open and lseek. Without these, performance might be poorer. Can't tell without testing, as micropython's io is likely different from that of cPython.

**Comment by stephan-ack** [comment]
I will try and test it tomorrow. Will return with some feedback :)

**Comment by stephan-ack** [comment]
But can you confirm that the micropython branch is updated? From a quick scrollthrough it seems it's still using python3 environment, still using lseek from the os library and not using io at all? :)

**Comment by QuirkyCort** [comment]
Yes. The micropython branch is updated. The lseek and os.open are still present, and the module will use them if it detects Python3. It only switches to io.open if it detects micropython. io.open is synonymous with open, so you won't see "io" in the code.

Again, please note that only the base sensor class and touch sensor are modified, so nothing else will work. I also did not test this at all, so the possibility of stupid mistakes are high. Sorry...

**Comment by stephan-ack** [comment]
Alright, no worries - I am pressed on time, so can't guarrentee that I will test it today, but will try my best.

**Comment by stephan-ack** [comment]
First test with color sensor returns the following error:
----------
Traceback (most recent call last):
  File "/home/robot/testmicroevfast/main.py", line 25, in <module>
  File "/home/robot/testmicroevfast/ev3fast.py", line 316, in reflected_light_intensity
  File "/home/robot/testmicroevfast/ev3fast.py", line 181, in mode
KeyError: mode
----------
Exited with error code 1.

**Comment by QuirkyCort** [comment]
Only the base sensor class and the touch sensor are modified, so the color sensor won't work. If it works on the touch sensor, I'll modify the rest of the sensors and motors.

**Comment by stephan-ack** [comment]
Hmm, okay. I misunderstood you.

I get this error now:

----------
Traceback (most recent call last):
  File "/home/robot/testmicroevfast/main.py", line 21, in <module>
  File "/home/robot/testmicroevfast/ev3fast.py", line 228, in __init__
  File "/home/robot/testmicroevfast/ev3fast.py", line 72, in __init__
NameError: name 'FileNotFoundError' isn't defined
----------
Exited with error code 1.


My code on line 21.
touch = TouchSensor("in1")

**Comment by QuirkyCort** [comment]
Apparently, micropython throws a different error from python when the file is not found. I've made the error checking more generic. Should clear this error now, but not sure if there are any other differences between python and micropython that I'm not aware of.

**Comment by Mahlzeit2000** [comment]
Hi Cort,

I've tried it out with the touch sensor:

#!/usr/bin/env micropython
from ev3fast import TouchSensor
touchSensor = TouchSensor('in3')



Traceback (most recent call last):
  File "./mp_ev3fast.py", line 3, in <module>
  File "/home/robot/ev3fast.py", line 228, in __init__
  File "/home/robot/ev3fast.py", line 88, in __init__
  File "/home/robot/ev3fast.py", line 101, in _pre_open
TypeError: can't convert 'int' object to str implicitly

**Comment by QuirkyCort** [comment]
Fixed. Missed out one of the open still using the os.O_RDONLY. Sorry.

**Comment by dk88711** [comment]
Can we replace `os.lseek` to `fd.seek` ? Seems to work, but I don't know if they have differences.

**Comment by stephan-ack** [comment]
I do no longer have access to an EV3 brick, so I cannot provide anymore debugging.
Hopefully @dk88711 and/or @Mahlzeit2000 can be of assistance?

**Comment by dk88711** [comment]
[ev3fast_micropy.py](https://pastebin.com/eZt8vUXM)

**Comment by dk88711** [comment]
I tweaked some lines for better finding devices path, it may only works on micropython, and address is always needed to initialize a device.

Only tested for ultrasonic sensor. The other motors/sensors haven't tested yet. May be someone can help testing for all other devices.
The benchmark result (for reference only)
`for i in range(0, n): ev3fast_ultraSensor.distance_centimeters`
```
py3      ev3dev   353.61 lps
        ev3fast 1 632.85 lps
micropy  ev3dev   404.20 lps
        ev3fast 3 372.13 lps
```
`for i in range(0, n): print(ev3fast_ultraSensor.distance_centimeters, file=sys.stderr)`
```
py3      ev3dev   182.71 lps
        ev3fast   398.15 lps
micropy  ev3dev   257.96 lps
        ev3fast 1 289.81 lps
```
(though the actual update rate for the sensor is much lower than 1000 lps)
